spring:
    sql:
        init:
            mode: always
    datasource:
        url: jdbc:h2:mem:f72eba81-9ce6-4fd6-805c-2bd144d64e53
        username: sa
        password:
        driver-class-name: org.h2.Driver
    h2:
        console:
            enabled: true
    jpa:
        defer-datasource-initialization: true
        properties:
            hibernate:
                format_sql: true
                show_sql: true
server:
    port: 9090
